### PR TITLE
Remove the cache for the database

### PR DESCRIPTION
**Pull request by johscheuer**
So far we've seen more issues with the cache then it solved and I'm not sure if actually helps that much.

### CODE REVIEW

**Comment by brownleej** [comment]
I think it would be good to run a local test with this and perform a handful number of operations, and see if it produces a bunch of different connected clients in the database status.

**Comment by johscheuer** [comment]
I'll run some tests tomorrow 👍

**Comment by johscheuer** [comment]
So far my test only showed 3 connected clients (I assume because of the multi-version client since we use 3 versions)

**Review by brownleej — APPROVED** [review]
👍

**Pull request merged**
