### PR TITLE
Initial support for IPv6 clusters

### PR DESCRIPTION
**Pull request by johscheuer**
This PR adds the capability to manage IPv6 FDB clusters running in a Kubernetes IPv6 only cluster

With the changes I'm able to bootstrap a FDB cluster with IPv6:

```bash
$ kubectl get nodes -o wide
NAME       STATUS   ROLES    AGE   VERSION   INTERNAL-IP                          EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION   CONTAINER-RUNTIME
master     Ready    master   18h   v1.19.2   fd4a:fc40:8cfb:0:5054:ff:fea2:8107   <none>        Ubuntu 20.04.1 LTS   5.4.0-1024-kvm   containerd://1.3.3-0ubuntu2
worker-0   Ready    <none>   18h   v1.19.2   fd4a:fc40:8cfb:0:5054:ff:fe4e:fac6   <none>        Ubuntu 20.04.1 LTS   5.4.0-1024-kvm   containerd://1.3.3-0ubuntu2
worker-1   Ready    <none>   18h   v1.19.2   fd4a:fc40:8cfb:0:5054:ff:feb6:bec4   <none>        Ubuntu 20.04.1 LTS   5.4.0-1024-kvm   containerd://1.3.3-0ubuntu2
worker-2   Ready    <none>   18h   v1.19.2   fd4a:fc40:8cfb:0:5054:ff:fe4a:ebea   <none>        Ubuntu 20.04.1 LTS   5.4.0-1024-kvm   containerd://1.3.3-0ubuntu2

```

and the coordinators are listening on the IPv6 addresses:

```bash
fdb> coordinators
Cluster description: sample_cluster
Cluster coordinators (3): [fd44:fe56:7891:2f3a:901a:62f2:12d3:88c2]:4500,[fd44:fe56:7891:2f3a:9905:f003:c7bd:fb0d]:4500,[fd44:fe56:7891:2f3a:fd43:e24:a84c:2b37]:4500
Type `help coordinators' to learn how to change this information.
```

the cluster is healthy and can be used:

```bash
 kubectl get fdb
NAME             GENERATION   RECONCILED   HEALTHY
sample-cluster   1                         true
```

There are some minor issues with bouncing the processes that will be fixed before we can merge these changes.

Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/85 -> I would create an additional issue fur dual-stack and the transition from an IPv4 cluster to an IPv6 (or dual-stack) cluster.

- [ ] run `pytest`  in github actions
- [ ] Open issue for dual-stack support
- [ ] Update docs
- [x] Fix failing tests
- [x] Fix bouncing processes (process address parsing is broken)

### CODE REVIEW

**Comment by johscheuer** [comment]
It probably makes the most sense to refactor `addresses []string` to `addresses []ProcessAddress` in order to prevent a lot of parsing in the controller.

**Comment by johscheuer** [comment]
Given the current size of the PR I would open an additional PR for adding a GitHub action running `pytest`.

To document the current limitation (either IPv4 or IPv6 and no transition between IPv4 and IPv6 since this would require dual-stack) for the IP versions I would prefer https://github.com/FoundationDB/fdb-kubernetes-operator/blob/master/docs/compatibility.md as the right place or is there a better place @brownleej ?

**Comment by brownleej** [comment]
I think the user manual is the best place to document limitations like that.

**Comment by johscheuer** [comment]
I close this for now and hopefully I can finish this in the future.

**Pull request closed without merging**
