### PR TITLE
Add e2e test setup for operator

### PR DESCRIPTION
**Pull request by johscheuer**
# Description

This change adds the operator related e2e tests into the operator repository and allows users to run those e2e tests.

## Type of change

*Please select one of the options below.*

- New feature (non-breaking change which adds functionality)

## Discussion

I removed the old tests, since they never ran automatically.

## Testing

-

## Documentation

I will add more documentation once we move forward with the refactoring.

## Follow-up

-

### CODE REVIEW

**Review by johscheuer — COMMENTED** [review]
I have to add a build tag to the e2e test files to make sure we are not executing them when running `go test ./...`

**Comment by johscheuer** [comment]
> ### Result of fdb-kubernetes-operator-pr on Linux CentOS 7
> * Commit ID: [5706d58](https://github.com/FoundationDB/fdb-kubernetes-operator/commit/5706d5811ac158d6e6563c96aaee48be5b7e3e30)
> * Duration 3:09:27
> * Result: ❌ **FAILED**
> * Error: `Error while executing command: if $fail_test; then exit 1; fi. Reason: exit status 1`
> * [Build Log](https://d1e0l78xbkh3xa.cloudfront.net/fdb-kubernetes-operator/fdb-kubernetes-operator-pr/cf45baf0-4f8d-4152-8205-a75a84b53cff.gz) terminal output (available for 30 days)
> * [Build Workspace](https://d1e0l78xbkh3xa.cloudfront.net/fdb-kubernetes-operator-pr/cf45baf0-4f8d-4152-8205-a75a84b53cff/workspace.zip) zip file of the working directory (available for 30 days)

Test failure is related to this issue: `ERROR: This exclude may cause the total free space in the cluster to drop below 10%.\n` we have a fix for this in fdbcli and we are investigating it further from FDB side.

**Review by jleach4 — APPROVED** [review]
I do think we need to make a documentation run through this repo.  In the open source world, undocumented code is not well received…

**Comment by johscheuer** [comment]
> I do think we need to make a documentation run through this repo. In the open source world, undocumented code is not well received…

Let me spend some time today/this week on adding better documentation to this repo.

**Pull request merged**
