### PR TITLE
Change the useUnifiedImage setting to a more generic imageType

### PR DESCRIPTION
**Pull request by johscheuer**
# Description

Following the best practices from: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#primitive-types

## Type of change

- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Discussion

This is a breaking change but since the feature is currently not usable I think it's fine to change it anyways. We should make sure to announce it in the release notes but from my point of view the risk is minimal as we haven't released the unified image yet.

## Testing

Unit tests.

## Documentation

-

## Follow-up

-

### CODE REVIEW

**Comment by johscheuer** [comment]
> ### Result of fdb-kubernetes-operator-pr on Linux CentOS 7
> * Commit ID: [b0c09c4](https://github.com/FoundationDB/fdb-kubernetes-operator/commit/b0c09c4529ad3be26123349a749ab351157316d9)
> * Duration 2:54:06
> * Result: ❌ **FAILED**
> * Error: `Error while executing command: if $fail_test; then exit 1; fi. Reason: exit status 1`
> * [Build Log](https://d1e0l78xbkh3xa.cloudfront.net/fdb-kubernetes-operator/fdb-kubernetes-operator-pr/00302623-0562-4fca-803e-3630f1a6bc93.gz) terminal output (available for 30 days)
> * [Build Workspace](https://d1e0l78xbkh3xa.cloudfront.net/fdb-kubernetes-operator-pr/00302623-0562-4fca-803e-3630f1a6bc93/workspace.zip) zip file of the working directory (available for 30 days)

```text

  2024/05/28 15:25:16 finished all tests, start deleting namespace pr-865-vrtxhka6
• [FAILED] [376.722 seconds]
Operator Upgrades upgrading a cluster with a crash looping sidecar process [It] Upgrade from 7.1.57 to 7.3.33 with crash-looping sidecar [e2e, pr]
/codebuild/output/src1815370707/src/github.com/FoundationDB/fdb-kubernetes-operator/e2e/fixtures/upgrade_test_configuration.go:115

  [FAILED] Timed out after 120.000s.
  There is no failure as the matcher passed to Eventually succeeded on its most recent iteration
  In [It] at: /codebuild/output/src1815370707/src/github.com/FoundationDB/fdb-kubernetes-operator/e2e/test_operator_upgrades/operator_upgrades_test.go:271 @ 05/28/24 15:25:01.142
-----------------------------
```

🤔

**Comment by johscheuer** [comment]
> ### Result of fdb-kubernetes-operator-pr on Linux CentOS 7
> * Commit ID: [3c70687](https://github.com/FoundationDB/fdb-kubernetes-operator/commit/3c70687423ea3cdae409da181ed4ca52bf6d1b8c)
> * Duration 2:02:29
> * Result: ❌ **FAILED**
> * Error: `Error while executing command: if $fail_test; then exit 1; fi. Reason: exit status 1`
> * [Build Log](https://d1e0l78xbkh3xa.cloudfront.net/fdb-kubernetes-operator/fdb-kubernetes-operator-pr/11230494-a16d-4c8d-b434-60dbf23f936c.gz) terminal output (available for 30 days)
> * [Build Workspace](https://d1e0l78xbkh3xa.cloudfront.net/fdb-kubernetes-operator-pr/11230494-a16d-4c8d-b434-60dbf23f936c/workspace.zip) zip file of the working directory (available for 30 days)

```text
Summarizing 1 Failure:
  [FAIL] Operator HA Upgrades when no remote storage processes are restarted [It] Upgrade from 7.1.57 to 7.3.33 [e2e, pr]
  /codebuild/output/src1309749207/src/github.com/FoundationDB/fdb-kubernetes-operator/e2e/fixtures/ha_fdb_cluster.go:313
```

Seems unrelated 🤔

**Review by nicmorales9 — APPROVED** [review]
LGTM! I've also seen that e2e test fail sometimes, do we have an issue for it?

**Review by johscheuer — COMMENTED** [review]
> LGTM! I've also seen that e2e test fail sometimes, do we have an issue for it?

We have a few issues open for some test flakiness. In general some tests are failing because some of the test requirements are fairly strict and the EKS test setup can be a bit flaky if a lot of tests run concurrently.

**Pull request merged**
