### PR TITLE
Upload binaries instead of tar package

### PR DESCRIPTION
**Pull request by johscheuer**

### CODE REVIEW

**Comment by johscheuer** [comment]
Here is a test release: https://github.com/johscheuer/fdb-kubernetes-operator/releases/tag/v0.0.0.1233

**Review by JoshuaMcManus — COMMENTED** [review]
Do we also need to update the documentation on installing the binary since we'll no longer need to unzip the file?

**Comment by johscheuer** [comment]
> Do we also need to update the documentation on installing the binary since we'll no longer need to unzip the file?

Good, point I adjust the docs 👍

**Review by brownleej — APPROVED** [review]
👍

**Pull request merged**
