### PR TITLE
Correction of GetPublicIPsForPod and GetPodIPsForPod

### PR DESCRIPTION
**Pull request by mengzhbj**
# Description

Public IP and Pod IP are two different IP used by a pod, while Public IP is for public_address and Pod IP for listen_address in fdbmonitor.conf. If a pod doesn't have service, its Public IP will be the same as its Pod IP. But if a pod has a service, its Public IP will be different from its Pod IP. Before this PR, the old GetPublicIPsForPod() is more like about how to return pod's Pod IP. This PR differentiate them. 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Discussion

Welcome to discuss the design.

## Testing

With the code changes, I ran the operator to create internal services and external services(Load Balancer), then I checked the fdbmonitor.conf and found both public_address and listen_address work well.

Additional testing is welcomed once this is merged.

## Documentation

No, no need to update doc.

## Follow-up

N/A.

### CODE REVIEW

**Comment by brownleej** [comment]
I'm seeing errors from the integration checks in `locality_test.go`. Can you run `make test` on your branch to see if you can reproduce those errors?

**Review by johscheuer — COMMENTED** [review]
@mengzhbj friendly ping :) I just wanted to ask if you're able to continue your work on this?

**Comment by mengzhbj** [comment]
> @mengzhbj friendly ping :) I just wanted to ask if you're able to continue your work on this?

@johscheuer Yes, will do! Thanks for reminding

**Review by johscheuer — COMMENTED** [review]
@mengzhbj are you still planning on finishing this one? If not I would close this PR.

**Comment by johscheuer** [comment]
I'm going to close this. @mengzhbj if you still have time to work on this please feel free to reopen the issue.

**Pull request closed without merging**
