### PR TITLE
Add prefix factory option

### PR DESCRIPTION
**Pull request by hfu94**
This allows us to re-use existing clusters and can greatly fasten the testing time.

# Description

*Please include a summary of the change and which issue is addressed. If this change resolves an issue, please include the issue number in the description.*

## Type of change

*Please select one of the options below.*

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Documentation
- Other

## Discussion

*Are there any design details that you would like to discuss further?*

## Testing

*Please describe the tests that you ran to verify your changes. Unit tests?
Manual testing?*

*Do we need to perform additional testing once this is merged, or perform in a larger testing environment?*

## Documentation

*Did you update relevant documentation within this repository?*

*If this change is adding new functionality, do we need to describe it in our user manual?*

*If this change is adding or removing subreconcilers, have we updated the core technical design doc to reflect that?*

*If this change is adding new safety checks or new potential failure modes, have we documented and how to debug potential issues?*

## Follow-up

*Are there any follow-up issues that we should pursue in the future?*

*Does this introduce new defaults that we should re-evaluate in the future?*

### CODE REVIEW

**Comment by hfu94** [comment]
I have tested it with `replace github.com/FoundationDB/fdb-kubernetes-operator => /root/src/fdb-kubernetes-operator` in `go.mod`, it works now.

**Comment by hfu94** [comment]
sure, added

**Review by johscheuer — APPROVED** [review]
Thanks 👍

**Comment by hfu94** [comment]
from log I saw the error below, trying to see how this is related

```
[BeforeSuite] 
/codebuild/output/src39755650/src/github.com/FoundationDB/fdb-kubernetes-operator/e2e/test_operator/operator_test.go:86
  [FAILED] in [BeforeSuite] - /codebuild/output/src39755650/src/github.com/FoundationDB/fdb-kubernetes-operator/e2e/fixtures/factory.go:67 @ 06/23/23 14:40:44.294
[BeforeSuite] [FAILED] [0.000 seconds]
[BeforeSuite] 
/codebuild/output/src39755650/src/github.com/FoundationDB/fdb-kubernetes-operator/e2e/test_operator/operator_test.go:86

  [FAILED] Unexpected error:
      <*errors.errorString | 0xc000510490>: {
          s: "no fdb image is supplied",
      }
      no fdb image is supplied
  occurred
  In [BeforeSuite] at: /codebuild/output/src39755650/src/github.com/FoundationDB/fdb-kubernetes-operator/e2e/fixtures/factory.go:67 @ 06/23/23 14:40:44.294
```

**Pull request merged**
