### PR TITLE
Make sure we always check the sidecar to get the most recent information about the updated ConfigMap

### PR DESCRIPTION
**Pull request by johscheuer**
# Description

This change makes sure we are not using the ConfigMap Annotation to check if a Pod has all the recent files. This can be critical during upgrades when the Annotation was already updated to another value.

## Type of change

*Please select one of the options below.*

- Bug fix (non-breaking change which fixes an issue)

## Discussion

This will result in a higher resource consumption on the operator side since the operator has to do those requests in 2 different places.

## Testing

Unit tests and e2e tests will be running.

## Documentation

-

## Follow-up

-

### CODE REVIEW

**Review by sbodagala — APPROVED** [review]

**Comment by johscheuer** [comment]
The failure is:

**Review by johscheuer — COMMENTED** [review]
The test failure is indicating this:

```text
"reason":"NeedsBounce","message":"Spec require a bounce of some processes, but the cluster has only been up for 0.000000 seconds"
```

This test failure exposed a few new failure modes:

1.) The coordinator process was still reporting, even thought it's running in 7.1.27 (I have to double check the way the CC is calculating the FoundationDB cluster status in this case):

```json
      "c8dd8904031dfff5df292c2f328df269": {
        "address": "100.80.88.131:4500:tls",
        "class_type": "log",
        "roles": [
          {
            "role": "coordinator"
          }
        ]
      },
```

The coordinator change sub reconciler was correctly discovering that a coordinator change was required but it was not able to do that because the process was missing the command line and we were not filtering processes with missing localities:

```text
{"level":"info","ts":1679437384.8890889,"logger":"controller","msg":"Could not parse address from command_line","namespace":"test-operator-upgrades-702-dsert3ra","cluster":"fdb-cluster-26lkg3dy","reconciler":"changeCoordinators","process":"","command_line":""}
{"level":"info","ts":1679437384.8892977,"logger":"controller","msg":"Cluster does not have coordinators in the correct number of zones","namespace":"test-operator-upgrades-702-dsert3ra","cluster":"fdb-cluster-26lkg3dy","reconciler":"changeCoordinators","desiredCount":5,"coordinatorZones":{"fdb-cluster-26lkg3dy-log-2":1,"fdb-cluster-26lkg3dy-log-3":1,"fdb-cluster-26lkg3dy-log-4":1,"fdb-cluster-26lkg3dy-log-5":1}}
{"level":"info","ts":1679437384.8893151,"logger":"controller","msg":"Cluster has an unhealthy coordinator","namespace":"test-operator-upgrades-702-dsert3ra","cluster":"fdb-cluster-26lkg3dy","reconciler":"changeCoordinators","address":"100.80.88.131:4500:tls"}
{"level":"info","ts":1679437384.8893197,"logger":"controller","msg":"Deferring coordinator change","namespace":"test-operator-upgrades-702-dsert3ra","cluster":"fdb-cluster-26lkg3dy","reconciler":"changeCoordinators"}
```

Next the bounce sub reconciler was stuck because the non existing process was reporting an uptime of `0` (same issue was in the change coordinators).

```text
{"level":"info","ts":1679437393.4117334,"logger":"controller","msg":"Reconciliation terminated early","namespace":"test-operator-upgrades-702-dsert3ra","cluster":"fdb-cluster-26lkg3dy","subReconciler":"controllers.bounceProcesses","requeueAfter":30,"message":"Cluster needs to stabilize before bouncing"}
```

**Comment by johscheuer** [comment]
> ### Result of fdb-kubernetes-operator-pr on Linux CentOS 7
> * Commit ID: [54ce45b](https://github.com/FoundationDB/fdb-kubernetes-operator/commit/54ce45b7e62043bd08c81d264b108d6fb2c72efb)
> * Duration 3:42:50
> * Result: ❌ **FAILED**
> * Error: `Error while executing command: if $fail_test; then exit 1; fi. Reason: exit status 1`
> * [Build Log](https://d1e0l78xbkh3xa.cloudfront.net/fdb-kubernetes-operator/fdb-kubernetes-operator-pr/44130492-5729-4802-9fdf-e02044fcf7ae.gz) terminal output (available for 30 days)
> * [Build Workspace](https://d1e0l78xbkh3xa.cloudfront.net/fdb-kubernetes-operator-pr/44130492-5729-4802-9fdf-e02044fcf7ae/workspace.zip) zip file of the working directory (available for 30 days)

The operator was able to move forward but hit a known issue:

```text
{"level":"info","ts":1679475008.1037874,"logger":"controller","msg":"current exclusions","namespace":"test-operator-upgrades-703-cdxs9dxv","cluster":"fdb-cluster-xhftx1sl","reconciler":"excludeProcesses","ex":[]}
{"level":"info","ts":1679475008.1038988,"logger":"fdbclient","msg":"Running command","namespace":"test-operator-upgrades-703-cdxs9dxv","cluster":"fdb-cluster-xhftx1sl","path":"/usr/bin/fdb/7.1/fdbcli","args":["/usr/bin/fdb/7.1/fdbcli","--exec","exclude 100.80.22.169 100.80.10.11 100.80.55.50 100.80.36.5 100.80.33.83 100.80.14.110 100.80.20.176 100.80.45.95 100.80.57.87 100.80.4.0 100.80.53.172 100.80.35.127 100.80.31.200","-C","/tmp/74585094-e50d-4bcf-83cf-7b1a52fa9ce3","--log","--log","--trace_format","json","--log-dir","/var/log/fdb","--timeout","10"]}
{"level":"debug","ts":1679475008.103964,"logger":"events","msg":"Normal","object":{"kind":"FoundationDBCluster","namespace":"test-operator-upgrades-703-cdxs9dxv","name":"fdb-cluster-xhftx1sl","uid":"74585094-e50d-4bcf-83cf-7b1a52fa9ce3","apiVersion":"apps.foundationdb.org/v1beta2","resourceVersion":"686838154"},"reason":"ExcludingProcesses","message":"Excluding [100.80.22.169 100.80.10.11 100.80.55.50 100.80.36.5 100.80.33.83 100.80.14.110 100.80.20.176 100.80.45.95 100.80.57.87 100.80.4.0 100.80.53.172 100.80.35.127 100.80.31.200]"}
{"level":"error","ts":1679475008.2821064,"logger":"fdbclient","msg":"Error from FDB command","namespace":"test-operator-upgrades-703-cdxs9dxv","cluster":"fdb-cluster-xhftx1sl","code":1,"stdout":"ERROR: This exclude may cause the total free space in the cluster to drop below 10%.\nType `exclude FORCE <ADDRESS...>' to exclude without checking free space.\n","stderr":"","error":"exit status 1","stacktrace":"github.com/FoundationDB/fdb-kubernetes-operator/fdbclient.(*cliAdminClient).runCommandWithBackoff\n\t/workspace/fdbclient/admin_client.go:275\ngithub.com/FoundationDB/fdb-kubernetes-operator/fdbclient.(*cliAdminClient).ExcludeProcesses\n\t/workspace/fdbclient/admin_client.go:430\ngithub.com/FoundationDB/fdb-kubernetes-operator/controllers.excludeProcesses.reconcile\n\t/workspace/controllers/exclude_processes.go:84\ngithub.com/FoundationDB/fdb-kubernetes-operator/controllers.(*FoundationDBClusterReconciler).Reconcile\n\t/workspace/controllers/cluster_controller.go:166\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:121\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:320\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234"}
{"level":"info","ts":1679475008.2821891,"logger":"controller","msg":"Delaying requeue for sub-reconciler","namespace":"test-operator-upgrades-703-cdxs9dxv","cluster":"fdb-cluster-xhftx1sl","subReconciler":"controllers.excludeProcesses","message":"","error":"exit status 1"}
```

The operator was not able to exclude the "old" transaction processes:

```text
ERROR: This exclude may cause the total free space in the cluster to drop below 10%.\nType `exclude FORCE <ADDRESS...>' to exclude without checking free space.\n
```

CC @sbodagala

**Comment by johscheuer** [comment]
Probably fixed here too: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1254, I will double check that.

**Review by brownleej — CHANGES_REQUESTED** [review]
The code for this looks good, but given the complexity of the interactions here, I think it's especially important to have a test case that reliably reproduces the original bug. Could we try marking the monitor conf as read-only before doing the upgrade, so that the monitor conf gets stuck on the old version?

If we can, it would also be good to test a scenario where the old version of the sidecar can't terminate during the upgrade. This could lead to a scenario where the monitor conf looks "correct" based on the environment variables the sidecar is showing, but some other checks should catch it. If we don't already, we should explicitly check that the sidecar is running the expected version before calling any APIs on it. The check for the binary itself being present should catch this scenario as well.

**Comment by johscheuer** [comment]
```
• [FAILED] [5335.889 seconds]
Operator Upgrades upgrading a cluster and no coordinator is restarted [It] Upgrade from 6.3.25 to 7.1.27 with one coordinator not being restarted
/codebuild/output/src650683346/src/github.com/FoundationDB/fdb-kubernetes-operator/fdb-kubernetes-tests/tests/fixtures/command_line_flags.go:298

  [FAILED] Unexpected error:
      <*errors.errorString | 0xc0003b3a10>: {
          s: "timed out waiting for the condition",
      }
      timed out waiting for the condition
  occurred
  In [It] at: /codebuild/output/src650683346/src/github.com/FoundationDB/fdb-kubernetes-operator/fdb-kubernetes-tests/tests/fixtures/fdb_cluster.go:1820 @ 03/23/23 18:45:04.472
------------------------------
```

Same as the error before: `ERROR: This exclude may cause the total free space in the cluster to drop below 10%.`.

**Review by brownleej — APPROVED** [review]
After more discussion offline, I think manual testing is sufficient to merge the PR, and we can follow up with more end-to-end tests of these failure scenarios.

**Pull request merged**
