### PR TITLE
Version bump fdb binaries

### PR DESCRIPTION
**Pull request by JoshuaMcManus**
# Description

*Please include a summary of the change and which issue is addressed. If this change resolves an issue, please include the issue number in the description.*

## Type of change

*Please select one of the options below.*

- New feature (non-breaking change which adds functionality)

## Discussion

*Are there any design details that you would like to discuss further?*

No

## Testing

*Please describe the tests that you ran to verify your changes. Unit tests?
Manual testing?*

Tested pulling the image. 

*Do we need to perform additional testing once this is merged, or perform in a larger testing environment?*

No.

## Documentation

*Did you update relevant documentation within this repository?*

n/a

*If this change is adding new functionality, do we need to describe it in our user manual?*

No.

*If this change is adding or removing subreconcilers, have we updated the core technical design doc to reflect that?*

n/a

*If this change is adding new safety checks or new potential failure modes, have we documented and how to debug potential issues?*

n/a

## Follow-up

*Are there any follow-up issues that we should pursue in the future?*

No.

*Does this introduce new defaults that we should re-evaluate in the future?*

No.

### CODE REVIEW

**Review by johscheuer — COMMENTED** [review]
Should we also update the build version used in the Dockerfiles?

**Comment by JoshuaMcManus** [comment]
> Should we also update the build version used in the Dockerfiles?

For some reason those didn't show up when I searched for the version in the project. Updated them now!

**Review by brownleej — APPROVED** [review]
👍

**Review by johscheuer — APPROVED** [review]
Please also update https://github.com/FoundationDB/fdb-kubernetes-operator/blob/main/.github/workflows/pull_request.yml#L9 otherwise LGTM 👍

**Comment by JoshuaMcManus** [comment]
> Please also update https://github.com/FoundationDB/fdb-kubernetes-operator/blob/main/.github/workflows/pull_request.yml#L9 otherwise LGTM 👍

Already done ✅

**Pull request merged**
