### PR TITLE
Update RBAC settings for role and simplify secrets labelling

### PR DESCRIPTION
**Pull request by johscheuer**
Add the required rules to be able to use the operator via `kustomize`.

### CODE REVIEW

**Review by brownleej — APPROVED** [review]
👍

**Comment by brownleej** [comment]
@johscheuer The PRB is encountering uncommitted changes. Can you rebase this off of master, and then run `make clean all`, to see if it picks up new changes?

**Comment by johscheuer** [comment]
I forgot to set the right Kubebuilder annotations 🤦

**Review by brownleej — APPROVED** [review]
👍

**Pull request merged**
